name: CI

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN || '' }}
    strategy:
      matrix:
        java: [ '21' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: ${{ matrix.java }}
            cache: 'maven'

      - name: Verify
        run: mvn -B -ntp clean verify

      - name: Upload Fat JAR (Release Tags)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v4
        with:
          name: knox-token-utility-fat-jar
          path: target/knox-token-utility-*-jar-with-dependencies.jar

      - name: Upload Surefire Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/

      - name: Upload JaCoCo Coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: |
            target/site/jacoco/index.html
            target/site/jacoco/jacoco.xml
            target/site/jacoco/jacoco.csv

      - name: (Optional) Codecov Upload
        if: ${{ env.CODECOV_TOKEN != '' }}
        uses: codecov/codecov-action@v4
        with:
          files: target/site/jacoco/jacoco.xml
          flags: unittests
          fail_ci_if_error: false
