name: CI

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN || '' }}
    strategy:
      matrix:
        java: [ '21' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: ${{ matrix.java }}
            cache: 'maven'

      - name: Verify
        run: mvn -B -ntp clean verify

      - name: License Policy Check
        run: |
          ./scripts/license_policy_check.sh target/sbom.json || true
        env:
          BANNED_LICENSES: AGPL-3.0,SSPL-1.0

      - name: Vulnerability Scan (Grype)
        uses: anchore/scan-action@v3
        continue-on-error: true
        with:
          path: .
          fail-build: false
          output-format: sarif
          severity-cutoff: medium

      - name: Upload Vulnerability Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: vulnerability-scan
          path: grype.sarif
          if-no-files-found: ignore

      - name: Upload SBOM
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: |
            target/sbom.json
            target/sbom.xml
          if-no-files-found: ignore

      - name: Upload SPDX SBOM
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spdx-sbom
          path: |
            target/site/*.spdx.json
          if-no-files-found: ignore

      - name: Upload Fat JAR (Release Tags)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v4
        with:
          name: knox-token-utility-fat-jar
          path: target/knox-token-utility-*-jar-with-dependencies.jar

      - name: Upload Surefire Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/

      - name: Upload JaCoCo Coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: |
            target/site/jacoco/index.html
            target/site/jacoco/jacoco.xml
            target/site/jacoco/jacoco.csv

      - name: (Optional) Codecov Upload
        if: ${{ env.CODECOV_TOKEN != '' }}
        uses: codecov/codecov-action@v4
        with:
          files: target/site/jacoco/jacoco.xml
          flags: unittests
          fail_ci_if_error: false

      - name: Deployment Check
        if: always()
        run: |
          chmod +x scripts/check-deploy.sh
          ./scripts/check-deploy.sh --local --skip-server
        continue-on-error: true
