name: Publish to Maven Central

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
            distribution: temurin
            java-version: '21'
            cache: 'maven'
            server-id: central
            server-username: MAVEN_CENTRAL_USERNAME
            server-password: MAVEN_CENTRAL_TOKEN
            gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
            gpg-passphrase: GPG_PASSPHRASE

      - name: Verify (no deploy) if snapshot
        if: contains(github.ref, '-SNAPSHOT')
        run: mvn -B -ntp clean verify -Dgpg.skip=false

      - name: Deploy Release
        if: startsWith(github.ref, 'refs/tags/v')
        run: mvn -B -ntp clean deploy -DskipTests=false -Prelease
        env:
          MAVEN_CENTRAL_USERNAME: _
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Show Built Artifacts
        run: ls -1 target || true
